service: poc-s3-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  profile: poc-backend-arena

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: arenabackend-poc-s3-storage
          event: "s3:ObjectCreated:*"
          existing: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "arenabackend-poc-s3-storage"
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: 
                - "*"
              AllowedMethods:
                - POST
                - PUT
              AllowedOrigins:
                - localhost
